name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

        run: |
          docker build -t ${{ env.IMAGE_NAME }}latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
          docker push ${{ env.IMAGE_NAME }}latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP  }}
          username: ${{ secrets.SSH_USER  }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
            docker pull ${{ secrets.DOCKER_USERNAME }}/latest
            docker stop interesting_matsumoto||true
            docker rm interesting_matsumoto||true
            docker run -d --name interesting_matsumoto -p 3000:3000 ${{ env.IMAGE_NAME }}latest
