name: Deploy Next.js App

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Server
        env:
          HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            docker pull ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.PORT_MAPPING }}:${{ env.CONTAINER_PORT }} ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          "
