name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Run custom script
        run: ./run.sh
        # Ensure the script runs before anything else

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

        run: |
          docker build -t ${{ env.IMAGE_NAME }}latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
          docker push ${{ env.IMAGE_NAME }}latest

      - name: Deploy to Server
        env:
          HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
            docker pull ${{ secrets.DOCKER_USERNAME }}/latest
            docker stop interesting_matsumoto||true
            docker rm interesting_matsumoto||true
            docker run -d --name interesting_matsumoto -p 8080:3000 ${{ env.IMAGE_NAME }}latest
          "
